### ISSUE TITLE
Get this added to the celery core

### ISSUE THREAD

**Issue by ThiefMaster** [beniwohli/celery-redis-unixsocket#3]
> &lt;asksol> celery-redis-unixsocket I haven't heard about, what is it?
> &lt;ThiefMaster> https://github.com/piquadrat/celery-redis-unixsocket
> &lt;asksol> ok, I guess you could lobby the author to submit it as a pull request instead
> &lt;asksol> and I can add it or merge it into the existing redis backends

**Comment by beniwohli** [comment]
I'll see if I can come up with the time to make a proper pull request :)

**Comment by blaze33** [comment]
I know nobody got much time to work on this, I think I could make some time to work on this as a small side-project but I'm not really sure where to start – to do it the right way – so I'd like to invite everyone interested to help documenting the process step by step in the first place. (and if I can't do it anybody could take the lead with some initial info)

My previous experiences tell me we have a better chance to write an acceptable pull request by asking for advice first, not coding headfirst, sometimes into a wall :dizzy_face: !

Let's start:
- I opened an issue upstream:  https://github.com/celery/celery/issues/1283
- The configuration part should be improved to have `CELERY_RESULT_BACKEND` & `BROKER_URL` support the `file://` URI scheme. The current setup using `BROKER_HOST=/tmp/redis.sock` is kind of a hack. Not to mention that the `*_HOST` and `*_PORT` settings are now deprecated (removed in celery 4).

**Comment by blaze33** [comment]
This issue can be closed, celery-redis-unixsocket is now merged in kombu (an thus celery) :)

**Comment by beniwohli** [comment]
@blaze33 ẅow, thanks, this is awesome!

**Comment by jaap3** [comment]
Quick note: Kombu has redis+socket support in it's development tree, but there's no official release that supports this yet!

**Comment by DmytroLitvinov** [comment]
Hello @beniwohli .

It is added support for unix socker as a broker, but what about result backend? Will it work for result backend?

Will be appreciated for your answer.

**Comment by beniwohli** [comment]
Hi @DmytroLitvinov 

Unfortunately, I no longer maintain or use this module (or celery), so I'm unsure about the status of using unix socket connections to Redis as a result backend.

**Comment by DmytroLitvinov** [comment]
Thank, @beniwohli .

Maybe you could help @blaze33 ?
Really need help about supporting unix socket for result backend.
I saw you added support for transport layer, but did not find any notes about result backend via socket.
